hf_configuration:
  hf_dataset_name: mckinsey_state_of_ai_doc_understanding
  hf_organization: yourbench
  private: false

model_list:
  - model_name: google/gemini-2.5-flash
    base_url: https://openrouter.ai/api/v1
    api_key: $OPENROUTER_API_KEY

pipeline:
  ingestion:
    llm_ingestion: true
    source_documents_dir: example/rich_pdf_extraction_with_gemini/data
    output_dir: example/rich_pdf_extraction_with_gemini/processed
  summarization:
  chunking:
  single_shot_question_generation:
  multi_hop_question_generation:
  cross_document_question_generation:
  prepare_lighteval:
  citation_score_filtering: