hf_configuration:
  hf_dataset_name: prompt_examples_demo
  hf_organization: yourbench
  private: true

model_list:
  - model_name: Qwen/Qwen3-235B-A22B
    provider: fireworks-ai

pipeline:
  ingestion:
    source_documents_dir: example/data/raw
    output_dir: example/data/processed
  
  summarization:
    # Example 1: Use default prompt (empty string falls back to module default)
    summarization_user_prompt: ""
    combine_summaries_user_prompt: ""
  
  single_shot_question_generation:
    # Example 2: Load prompt from file
    single_shot_system_prompt: "example/custom_prompts/my_custom_prompt.md"
    # Example 3: Inline custom prompt string
    single_shot_user_prompt: |
      Please analyze this text and create exactly 2 questions:
      
      <text_chunk>
      {text_chunk}
      </text_chunk>
      
      Focus on conceptual understanding rather than factual recall.
  
  multi_hop_question_generation:
    # Use defaults by leaving empty
    multi_hop_system_prompt: ""
    multi_hop_user_prompt: ""