name: Quality

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - v*-release
  pull_request:
    branches:
      - main

jobs:

  check_code_quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff==0.8.4

      # Step 4: Run Makefile quality command
      - name: Run code quality check
        run: make quality
